services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: workservice-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123!"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: WorkService.Api/Dockerfile
    container_name: workservice-api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=workservice-sql,1433;Database=WorkServiceDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;Encrypt=False"
    depends_on:
      - sql
